// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    escrow
    (
        init => init
        upgrade => upgrade
        deposit => deposit
        release => release
        refund => refund
        get_escrow => escrow_data
        get_validation_contract_address => validation_contract_address
        get_identity_contract_address => identity_contract_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
